### ISSUE TITLE
Considering publish a new version to NPM?

### ISSUE THREAD

**Issue by fi3ework** [ampproject/remapping#184]
Thanks for the great work! TS 5.0 has released and the downstream packages are trying to migrating to `moduleResolution: bunder`(such as Vite). But the latest version of remapping on NPM still relies a old version of `@jridgewell/gen-mapping` which lacks `exports.types` that will block TS 5.0 to find the type definition. I saw remapping has bumped the dependency. All we need to do is release a new version. Could the package maintainer do a new release? Thanks! 🤗

**Comment by jridgewell** [comment]
Done.
