### ISSUE TITLE
`exports` support

### ISSUE THREAD

**Issue by benmccann** [ampproject/remapping#192]
It would be great to add `exports` to the `package.json`. This is usually considered a breaking change though, so would probably best be done in a major version release. If you're open to the change, either now or potentially in the future, I'd be happy to send a PR

**Comment by jridgewell** [comment]
It's already there: https://github.com/ampproject/remapping/blob/395a8e7ef55138d9c889214983e351cf48b0b530/package.json#L13-L23

**Comment by benmccann** [comment]
ah, thanks! sorry for the false report. I was looking at an older minor
